version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: num-cortas-nginx
    ports:
      - "3015:80" # Map port 80 on the host to port 80 in the container
    volumes:
      - ./build:/usr/share/nginx/html:ro # Mount the build folder as Nginx's root
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro # Optional: Mount a custom Nginx config
    restart: always
